### ISSUE TITLE
Princeton Hack - @platform Tech Workshop, Nov. 5, 6:00 to 7:00 pm, pacific

### ISSUE THREAD

**Issue by atsigndenise** [atsign-foundation/events#38]
We have been given a Friday night workshop slot from 6:00 to 7:00 pm pacific.

- [ ] Develop workshop material (general @ platform overview slides)
- [ ] Determine who will lead and join the workshop @TylerTrott @XavierChanth will demo @ app and revamp an old demo app.
- [x] Dry run scheduled

**Comment by XavierChanth** [comment]
Spoke to Denise, can close this.
