### ISSUE TITLE
Princeton Hack - Prep and Train Hack Princeton Student to Man Our Booth

### ISSUE THREAD

**Issue by atsigndenise** [atsign-foundation/events#42]
We will have a dedicated booth for the on campus hackers.  We have been offered a dedicated student to get trained, prepared and help hackers on site.  The booth will have our t-shirts and stickers.  They would like QR Codes so that students can go directly to the key dev site pages they need.

- [x] Meeting with student, Xavier @atsigndenise 
- [x] Work with student so that they have everything they need @atsigndenise @XavierChanth
  - [x] Provide Flutter resources
  - [x] atsign.dev
  - [x] Youtube
  - [ ] Active learning - have the student code a basic application
- [ ] Follow up and answer any questions
- [ ] Create QR codes for the booth to provide quick access to our resources (Sy)

**Comment by XavierChanth** [comment]
Spoke to Denise, can close this.
