### ISSUE TITLE
Princeton Hack - Pre-Hack Preparation for Hackers

### ISSUE THREAD

**Issue by atsigndenise** [atsign-foundation/events#44]
There may be an opportunity to gain greater readiness for hackers. 
 
- [x] Simple participants checklist to help them prepare @atsigndenise @TylerTrott @nickelskevin @cconstab 
- [ ] Send recommended free Flutter courses @atsigndenise @XavierChanth will come up with reccomendations
- [ ] Get your @ sign (participants)
- [ ] Provide them with our Discord 
- [ ] [Create check-list](https://docs.google.com/document/d/1yTmUk8cy3iPlAMyqz8MuSQiHgqRMuZnjIhzG0lg976w/edit) for distro @anthonyvprakash @XavierChanth

**Comment by nickelskevin** [comment]
@atsigndenise - can we close this issue?

**Comment by XavierChanth** [comment]
Spoke to Denise, can close this.
