### ISSUE TITLE
@ mosphere Pro Contest at Hack This Fall : Dec 2021

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/events#52]
Lead: @anthonyvprakash 

- [x] Content for Contest for @ mosphere Pro at Hack This Fall 
- [x] [Landing Page / Entry form](https://forms.gle/MXSKuw3kxw7prYSDA)
- [x] [Contest Rules](https://atsign.com/hack-this-fall-atmosphere-pro-contest-terms/)
- [x] Prizes
- [x] Logistics
- [x] Get landing page on .com site ready for atmosphere Pro by Dec 8 - @rtilney 
- [x] Launch Campaign
- [x] T-shirt distribution for winners

**Comment by rtilney** [comment]
@anthonyvprakash Can you provide a link to the brief or content for this page? Thank you!

**Comment by anthonyvprakash** [comment]
The work is done. The campaign needs to be launched.

**Comment by anthonyvprakash** [comment]
All activities complete.
