### ISSUE TITLE
Video & Written Content Publishing: @spacechat

### ISSUE THREAD

**Issue by Sahil-Mehta881** [atsign-foundation/events#59]
Lead: @Sahil-Mehta881 
Publish video and written @spacechat first follower content, and lay the foundation for video editing future content

- [x] Set up relationship with a video editor on Fiverr for long-term video content projects @hakeemawbrey  @Sahil-Mehta881 
- [x] Create a transcript of specific 2-3 minutes of first follower interview for editor to use @Sahil-Mehta881 
- [x] Publish final article on Flutter Medium @hakeemawbrey  @Sahil-Mehta881 @anthonyvprakash

**Comment by hakeemawbrey** [comment]
Update as of April 6th

- [ ] highlights in transcript completed 
- [ ] feature graphic created
- [ ] transcript and vid sent to editors Wednesday night
- [ ] medium article sent to flutter community but not accepted yet
