### ISSUE TITLE
Github Externship planning

### ISSUE THREAD

**Issue by ghost** [atsign-foundation/events#60]
GitHub Externship is a 90-day fellowship program for students to work on Open Source & DevSecOps projects. We would be taking 2-3 externs in our company to work on some open-source Dev and new apps.

More info on Github externship here - https://docs.google.com/document/d/1-keIov7jotdZkV_z7_OPGrf-uPiwEEfdJGH8ioi3-Wg/edit?usp=sharing

 - [x] Fill in the form for org registration.
- [ ] Brainstorm apps and features to be included in the Externship workflow.
- [ ]  List out a detailed doc on the dos and don'ts of externship at the company.

**Comment by Jatinpandya26** [comment]
GitHub Externship is a 90-day fellowship program for students to work on Open Source & DevSecOps projects. We would be taking 2-3 externs in our company to work on some open-source Dev and new apps.

More info on Github externship here - https://docs.google.com/document/d/1-keIov7jotdZkV_z7_OPGrf-uPiwEEfdJGH8ioi3-Wg/edit?usp=sharing

- [ ] Fill in the form for org registration.
- [ ] Brainstorm apps and features to be included in the Externship workflow.
- [ ] List out a detailed doc on the dos and don'ts of externship at the company.

**Comment by anthonyvprakash** [comment]
The activity is cancelled for 2022
